### PR TITLE
Simplifies code contributions & reviews by automating the dev automating the dev envirmoment.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! there, :slightly_smiling_face:

this PR simplifies code contributions by fully automating the development setup with Gitpod. With a single click, it'll launch a workspace and automatically:

- clone the water.css repository.
- install the dependencies.
- run `yarn dev`.

So that anyone interested in contributing can start straight away.

You can give it a try on my fork of the repo: https://gitpod.io#https://github.com/nisarhassan12/water.css

image

It seems to work well! Please let me know if there is anything that can be improved. I would love to help :)

### CODE REVIEW

**Comment by jonaskuske** [comment]
I think we should coordinate this and recommended only one solution for in-browser development. Either Repl.it (which we currently link to), Gitpod, or GitHub's built-in [Codespaces](https://github.com/features/codespaces/) for which you can already request early-access. The latter naturally has the best integration with GitHub, however their pricing is not published yet so we don't know if they'll still have a free tier after the beta phase is over. I'd suggest waiting until Codespaces is out of beta before making a decision.

cc @kognise

**Comment by kognise** [comment]
I like Repl.it and I'm happy to put some effort into getting it working smoothly, but I'm obviously biased because I basically work for them :joy:

Something I don't like as much about Gitpod is the fact that you need to sign up for an account before being able to edit/run code. I'm excited for Codespaces but as you said, the pricing hasn't been released yet.

**Comment by kylejrp** [comment]
Marking this as on hold until GitHub Codespaces pricing is released. I'm up for supporting any (or all?) of the options.

**Comment by kognise** [comment]
I'm gonna close this, Codespaces came out and is free!

**Pull request closed without merging**
