### PR TITLE
Remove dist folder

### LINKED ISSUE #109: Remove `dist` folder
The `dist` folder should be removed in favor of publishing these build artifacts through npm. We would want to remove these files, add `dist` to `.gitignore` and create a new `.npmignore` that excludes the same files as `.gitignore` except for the `dist` folder.

This will make pull requests easier to review and prevent contributors from having to build beforehand.

This is probably a breaking change and should be done with the release of 2.0.0.

### PR DESCRIPTION
**Pull request by melanieseltzer**
Closes #109

Opted for a files whitelist in package.json instead of an .npmignore, as it seems to be easier to maintain. What do you think? Also, have added a `prepublishOnly` script so the build gets run automatically before publishing.

### CODE REVIEW

**Comment by kylejrp** [comment]
This looks great! Thanks for the quick work.

I'm not familiar with the difference between an `.npmignore` and the file whitelist. Do you have any resources you could send? 

I'll do some more research tonight and review this pull request so we can get it merged in. Thanks so much for your contribution!

**Comment by melanieseltzer** [comment]
Thanks for the merge 🎉 

@kylejrp In the end I think either would be fine but I tend to favor the `files` whitelist key for its simplicity and for being explicit about what you want to include. And since npm automatically ignores the stuff in .gitignore there's no need to manage two ignore files. [This article](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d) also goes over what could go wrong with npmignore (though not sure if that applies anymore as in the article they state that npm now displays the files which will be packed 🤷‍♀).

**Comment by jonaskuske** [comment]
👍🏻👍🏻

I'm also very much in favor of using the existing `.gitignore` in combination with `files[]` instead of managing a separate blacklist – and nice work with the `prepublishOnly` script!

It's part of the steps I had outlined here: https://github.com/kognise/water.css/pull/64#issuecomment-497712344 :)

**Comment by kylejrp** [comment]
Hey @melanieseltzer (or anyone else that thinks they could help!),

There's a bunch of outstanding pull requests that previously ran `yarn build` before we merged this in. These pull requests now have merge conflicts that want to add in new files in `dist`. What's the best way to resolve these merge conflicts? I'm hoping there's something we can do to get their merge request in compliance with the newly updated `.gitignore` file. I'm not seeing an obvious path for this though...

Any help or recommendations would be appreciated! 😁

**Comment by melanieseltzer** [comment]
@kylejrp I believe deleting the `dist` folder entirely should do the trick - just need to merge master into the branch, get notified of the conflict, go and delete the folder and all its contents, then `git commit` to mark it as resolved. Or there's a [mergetool](https://stackoverflow.com/a/41364780) option but I've never used that before so YMMV...

**Comment by jonaskuske** [comment]
Yep! Proactively deleting the `dist/` directory from the respective branches without attempting to merge should work as well, I suppose. (if the dist files are the sole cause for the conflicts)

**Comment by kylejrp** [comment]
Perfect, I really appreciate your help @melanieseltzer and @jonaskuske. You rock! 🎸

**Pull request merged**
