### PR TITLE
[Blockquotes] Added background and new file for blockquote

### PR DESCRIPTION
**Pull request by FedeAPerez**
Objetives:
* Making the blockquotes element similar to the other UI elements using border radius 6px and background.
* Making the _variables file for using elements like spacing, radius and borders to make a consistant UI when using those elements.

### CODE REVIEW

**Comment by kognise** [comment]
Question: how is this better than #19?

**Comment by FedeAPerez** [comment]
I'm actually making use of that PR but adding things that makes the elements more cohesive. I think that it needs to be consistant across all elements, more like a material-ui kind of thing but for beginners. What's more, I think that it's possible to create an ecosystem using water.css and something to make small components for blogs and ecommerce sites that doesn't want to (or can't) handle really big code based. Let me know if we share the vision and I'm able to make more and more things in the project.

**Comment by kognise** [comment]
Yeah, that could be great! I'm also really looking forward to #18 which proposes making Water.css a Jekyll theme.

**Comment by FedeAPerez** [comment]
Let me correct the dist and then we can see if the PR it's good to go.

**Comment by kognise** [comment]
Thanks! Taking a look

**Comment by FedeAPerez** [comment]
I have a lot of free time this weekend, let me know and I will help you with other things for the project. Regards!

**Comment by kognise** [comment]
@FedeAPerez Oh, awesome! Thanks so much. Do you have a discord or other preferred method of communication?

Also, do you think this is ready to merge?

image

image

**Comment by kognise** [comment]
If you don't mind I've removed the variables file - I'm interested in something like that but I'd rather split it into a seperate PR. Thanks for all your changes!

**Comment by kognise** [comment]
:shipit:

**Comment by FedeAPerez** [comment]
Sorry for the late response.
For communication: I use Slack a lot, so if you use it, I'll be ready to go.
In terms of the pr: I think it's a little improvement in terms of background radius and color, it fits more with the theme and has more consistency across the elements of the UI but if you had something else in mind let me know. Maybe we need a way to share thoughts (eg. Sketch) in terms of what the user should see in the basic theme.

Also: I'm more than ok with making another pr specific for vars in the future.

**Comment by kognise** [comment]
@FedeAPerez Awesome, thanks! How can I contact you on Slack?

Design-wise, this is kinda hard. I don't have access to Sketch or Adobe XD because I'm on Linux. Maybe we could use Figma?

**Pull request merged**
