### PR TITLE
[supersedes #58] Add arrow for <select>

### LINKED ISSUE #57: Style of <select>
I really love the library ❤️ but I think the `<select>` tag needs some adjustment.
It is hard to see a difference to a simple button.
Bildschirmfoto 2019-04-20 um 16 47 05

Maybe an inline `svg` can be added to show that it is a `<select>`.
```
select {
  background: #949494
    url("data:image/svg+xml;utf8,<svg viewBox='0 0 140 140' width='24' height='24' xmlns='http://www.w3.org/2000/svg'><g><path d='m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z'/></g></svg>")
    no-repeat;
  background-size: 12px;
  background-position: calc(100% - 15px) 57%;
  background-color: #efefef;
  padding-right: 35px;
}
```

Something like this looks good.
Bildschirmfoto 2019-04-20 um 16 52 36

Thank you for this cool lib :)

### PR DESCRIPTION
**Pull request by jonaskuske**
I took the liberty to update #58 so it aligns with our CSS-variable powered codebase:

1. Rebased [IL4Miy/water.css](https://github.com/IL4Miy/water.css) on current master, so it can be merged again
(and so that @IL4Miy still appears as a contributor in our git history :) )
2. Added [`postcss-inline-svg`](https://github.com/TrySound/postcss-inline-svg) to inline the SVGs instead of loading them through `url()`
3. Restructured the build to use a single file `select-arrow.svg` for both dark & light versions, as you can specify the desired color while inlining with the `svg-load()` function of `postcss-inline-svg`
4. Updated the cssnano config so the SVG is more heavily minified¹
5. Tested the result in Chrome, Firefox, Edge (EdgeHTML) and Internet Explorer. Not in Safari unfortunately, as I don't have Apple hardware.

Preview URL: https://deploy-preview-94--watercss.netlify.com/

Note: I didn't `yarn build` yet so you can better see the changes. Why don't we just only `build` prior to publishing a new release?
&nbsp;

fix #57
close #58 

___

**¹** I reduced the `floatPrecision` to `0` so all numbers used in the SVG are rounded to an integer. This saves another ~50% – which we really need, as we now ship both the dark _and_ the light arrow in our non-standalone builds. The resulting SVG looks a bit funny when opened in an image viewer at large size, but perfectly fine in the browser, even at maximum zoom level.

### CODE REVIEW

**Comment by jonaskuske** [comment]
> I think you mentioned before that we can get rid of the builds once we switch to npm distributed releases anyways, right?

Yep, exactly :)
I also described the steps needed for this [here on the npm PR. (#64)](https://github.com/kognise/water.css/pull/64#issuecomment-497708041)

> Actually, there's some (hopefully easy) merge conflicts that I can't see through Github's merge conflict UI. Do you mind resolving these?

Done. Both the recent text-semantics PR and this one added some variables to the end of the respective files, was indeed an easy fix 👍🏻

**Comment by IL4Miy** [comment]
@jonaskuske Great work! Thank's

**Comment by kognise** [comment]
After merging in the changes from master the box isn't rendering properly - lemme take a look at this

**Comment by kognise** [comment]
Fixed!

**Comment by kognise** [comment]
Fixed! @kylejrp could you please take a look at this?

**Pull request merged**
