### PR TITLE
feat: Add <dialog> support

### PR DESCRIPTION
**Pull request by khuongduybui**
Fixes https://github.com/kognise/water.css/issues/139

### CODE REVIEW

**Comment by khuongduybui** [comment]
@kylejrp here you go

**Comment by khuongduybui** [comment]
We can add `backdrop-filter: blur(4px);` to `dialog::backdrop` for more dramatic effect.

**Comment by mateja176** [comment]
The preview looks really nice!

**Comment by khuongduybui** [comment]
I have updated / rebased this pull request upon version 2.

**Comment by kognise** [comment]
Looks great - I'm gonna make a few quick changes and then merge. Thanks!

**Review by kognise — APPROVED** [review]
:shipit:

**Pull request merged**
