### PR TITLE
add scrollbar stylings to code segments

### PR DESCRIPTION
**Pull request by DanielBiegler**
Title. See here: 

scrollbars

### CODE REVIEW

**Comment by kognise** [comment]
Personally I'd rather not have these, b/c it creates different visual styles from everything else and other scrollbars. Also, the only place this is likely to overflow in is on mobile and mobile browsers have nice scrollbars. Thoughts?

**Comment by DanielBiegler** [comment]
When I want to present some markup for example it can very easily overflow on desktop, then the default bars are insanely ugly.

I've been using prism.css to display code so far, and they also have styled scrollbars which would be a must for me.

**Comment by kognise** [comment]
Idea: maybe we could create custom scrollbars for the entire site, not just code blocks?

**Comment by DanielBiegler** [comment]
I think styling the textarea for example also would be great! Maybe styling the whole site then would be neat too, we can try?

**Comment by kognise** [comment]
Yeah! We have to watch file sizes, though... they're growing biiggere

**Comment by kognise** [comment]
Also, I'm not a big fan of the scrollbar styles - lemme pull this and get some work done :P

**Comment by kognise** [comment]
Ready to ship?

**Comment by kognise** [comment]
:shipit:

**Pull request merged**
