### PR TITLE
Add eslint, husky and prettier for commit automation

### PR DESCRIPTION
**Pull request by jackson-elfers**
This pr goes along with #115 but I believe extends on that idea with building, linting and formatting being automated upon commit. I've also taken the liberty to convert this project to an npm based installation as yarn wasn't playing nice with eslint (you'll notice a package-lock.json file). Everything works optimally as far as I can sense. Here are the new additions:
1) converted from yarn to npm based installation
2) installed eslint, husky prettier and lint-staged
3) added .eslintrc.json and .eslintignore file
4) changed prepublishOnly to "npm run build" (might take this out entirely since build is automated)
5) updated contribute docs for "npm install" and "npm run dev"
6) removed /dist from .gitignore

Run 'npm install' make a small change and commit to see it in action. If you like the idea and want me to make changes, give me a holler. I'm really quite new to open src collab so please feel free to give me critical pointers.

PS: It appears someone tried to remove the dist/ from .gitignore at one point even though it's still present. I took it out so the build ends up in the repo as I think somebody intended it to.

### CODE REVIEW

**Comment by jonaskuske** [comment]
Hey there, thanks for contributing! I'm personally very much a fan of automating these linting/formatting steps upon commit!

A couple notes:

1. I'm not sure to which extent this PR "goes along with" #115 rather than being in conflict. I love prettier, especially because it formats almost everything including JSON and Markdown, but I don't think we should add multiple potentially conflicting formatting scripts so we'll probably need to decide on one.
2. I think moving from yarn to npm isn't really in scope here and should optimally be a separate PR, though it might be okay. Anyway, how did yarn interfere with eslint? And I'm generally in favor of switching to npm – I *personally* prefer yarn, but npm has broader adoption and thus makes it easier for people to contribute I think.
3. We'll need the `prepublishOnly` script for automated releases from Continuous Integration, so please leave it in.
4. Adding `/dist` to `.gitignore` was intentional. We aim to remove build artefacts from GitHub and distribute `water.css` through npm starting with the next release. So you might want to revert that change, it will also make the "Changed Files" view a lot cleaner so it's easier to do Code Review! :)
5. I'd suggest some improvements to the pre-commit hook: since builds are handled separately from GitHub now, the build step can be removed. Also, I'd run all the linting and formatting through `lint-staged` so only staged files are affected. So we'd have something along the lines of

```json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": ["eslint --fix", "prettier --write", "git add"],
    "*.{css,html,json,md}": ["prettier --write", "git add"]
  }
}
```

Also, we could potentially integrate prettier with ESLint through [`eslint-plugin-prettier`/`eslint-config-prettier`](https://github.com/prettier/eslint-plugin-prettier) so they play nice together. Although I think we don't need this if we use Standard for our JS rather than ESLint + Prettier. (can still use prettier for other asset types)

**Comment by jackson-elfers** [comment]
Ok awesome, thanks for such a detailed and kind reply. Sorry to barge in with all these ideas, I suppose it's a lot for one PR. Totally see your position on taking the build out of the repo. I'm a personal fan of npm. I'll have to try installing eslint with yarn again somewhere, might've been a network thing. So cool, I'll make those changes and get back to you.

**Comment by jackson-elfers** [comment]
Hi @jonaskuske I've completed the changes you've asked for and it works great. 👍 Let me know if anything else needs revising. Here's a list of additions:

1. added dist/ back into .gitignore
2. added .prettierignore to (just like the .eslintignore) ignore dist/
3. removed present but .gitignore listed files (including dist/) using "git rm -r --cached ."
4. adjusted scripts to apply changes exclusively through lint-staged (your improvements)
5. manually tested run scripts, committed changes which started husky and ran with no fuss

**Comment by kylejrp** [comment]
It looks like this is now conflicting with master after I merged #115.

The scope of this merge request is fairly large. @jonaskuske and/or @jackson-elfers, can you help me understand what the scope of the merge request is? Is this just changing our linting method to prettier? Are there any other changes in this?

**Comment by jackson-elfers** [comment]
I'm going to close this and separate into non-conflicting pr's.  This pr involved 1. Switching to npm, 2. adding eslint 3. adding lint-staged 4. adding prettier 5. adding husky 6. added some instructions to contribute for npm compatibility. Essentially a lot of moving parts, too many for one pr. I think the main essential would be adding commit automation for linting and formatting. So I'll work on that.

**Comment by kylejrp** [comment]
Awesome!  Thanks for your understanding @jackson-elfers. You've put a lot of hard work into this and I'm excited to see this split into multiple merge requests. Thank you for contribution and all of your patience!

**Comment by jackson-elfers** [comment]
Hey it's no problem. I've found it's satisfying to commit and have husky run my linter and formatter all in one go. Gives a sort of peace of mind even when working alone. All the best.

**Comment by kylejrp** [comment]
Much appreciated 😁

If you don't mind, would you please reference issues #142, #143, #144, or #145 if you think any of your new issues close them?

**Pull request closed without merging**
