### PR TITLE
Theming through CSS variables, (prefers-color-scheme)

### PR DESCRIPTION
**Pull request by jonaskuske**
## So, I got the changes described in #70 working!

Theming is now accomplished through CSS Variables & PostCSS.

The 6 builds I outlined in #70 (default, legacy and standalone for both dark and light) work.
The default and legacy builds successfully update to match `(prefers-color-scheme)`, tested in Firefox Nightly. (I think that's the only browsering supporting this on Windows)
The legacy and standalone builds work fine in Internet Explorer, the default one keeps the general look and feel (typography, spacing...) but loses colors and everything set through variables, as expected.

### Build process

The compilation now consists of two tasks as we need to compute variables before running Sass.

Let's look at the following example:

```css
:root {
  --base-color: #03a7ff;
  --derived-color: lighten(var(--base-color), 20%);
}
```

Since Sass's `lighten()` function won't know what to do with `var(--base-color)`, we need to replace that reference with the actual value *before Sass handles the styles* – even in the default builds which otherwise use uncompiled, native CSS variables. So we have 3 steps:
1. Inline variable references within the variable declarations themselves, so derived/computed values work.
2. Compile and bundle the styles with Sass.
3. Inline *all* variable references for standalone & legacy builds.

Currently, this works by having a small task process the variable files and then write the result to intermediate files (`src/variable.scss` → `src/_variables/_variable.scss`). Afterwards, the main task runs, and Sass imports from this *intermediate variable directory*, not the source files themselves. I couldn't get Sass to pick up the changes done by PostCSS in step 1 any other way. :(
If there's a less hacky way to do this I'd be more than glad to change this process, I'm just personally not that experienced with Gulp so that's the only way I could get it to work.

### Size

Before:
image

After:
image

As you can see, the standalone builds have exactly the same size as the builds before this change – which makes sense, they're literally the same thing.
The default builds with both dark *and* light theme included are currently `1 kB` heavier.
Considerations here:
  - Since we're shipping variables in production now, shorter variable names = smaller filesize. By using one-letter variable names as is common when minifying JS, that additional `kB` is already cut by 50%. But this way theming at runtime is less ergonomic, so there's no silver bullet here. Maybe having a prefix acting as namespace followed by a semantic shortcode is an option here, e.g. `--w-bd` or `--w-cd` (Water.css border and Water.css code).  
  - Adding a `browserslist` tailored to modern browsers with CSS variable support could potentially further reduce the file size by getting rid of some prefixes. [I already marked the relevant spot in the code](https://github.com/kognise/water.css/pull/71/files?file-filters%5B%5D=.js#diff-b9e12334e9eafd8341a6107dd98510c9R99), but some research regarding the exact settings needed for the `browserslist` is necessary.

### Deploys

...with three times the amount of build files and source maps, we really, really need to get this on `npm` so deploys can happen independently from GitHub and the tons of changed `dist` files don't mess up all the Commits/PRs. 😅

### Next steps

Obviously, documentation etc. still needs to be updated before merging this is even remotely an option, but I wanted to open this PR already so we can discuss, collaborate and review here ✌🏻

### CODE REVIEW

**Comment by jonaskuske** [comment]
Heh, didn't know we have this nifty deploy preview configured!
Open https://deploy-preview-71--watercss.netlify.com/ in Safari or in a dev version of Firefox, switch your system from dark to light mode and vice versa and see the magic happen :D

**Comment by kylejrp** [comment]
Great work @jonaskuske! I love that we can modify the theme by using devtools on the preview site. Here's my comments:

### Color Functions
I'm not a big fan the workaround to get ligthen/darken to work. It really complicates both the build process and the two variable files. Since we're only using these color functions in a couple of places, I see two options that could work better:
1. Stop using the preprocessor color functions and just use hardcoded values:

```
:root {
  --base-color: #03a7ff;
  --derived-color: #50c2ff;
}
```
2. Assign CSS variables using Sass variables:
```
$base-color: #03a7ff
:root {
  --base-color: $base-color;
  --derived-color: lighten($base-color, 20%);
}
```
We could also just have all the Sass variables in `light.scss`/`dark.scss` and then transparently assign them to CSS variables inside the main rules like `_forms.scss`:
```
/* light.scss */
$base-color: #03a7ff
```
```
/* _forms.scss */
:root {
  --base-color: $base-color;
  --derived-color: lighten($base-color, 20%);
}
```

I kind of like this because then `light.scss`/`dark.scss` don't have to change at all, we just complicate some of the inner workings of our `.scss` files.

### Gulp

I think that our styles function is trying to do too much now. This could probably be split out two or more functions that make it easier to work with. I don't mind cleaning this up, I've got some ideas in mind and I'm more comfortable with Gulp.

### Size concerns

We should be looking for our build tools to minify the css variable names if possible. I'm not really too worried about it though, because long variable names should compress nicely in gzip. (We should test and compare the gzip sizes - I suspect that long variable names will compress to a similar size to short variable names.)

### Deploys

Can you explain more how publishing to NPM will clean up our distribution folder? I haven't published a package to NPM before.

**Comment by jonaskuske** [comment]
### Color functions

1. Yup, with the little usage of `lighten()/darken()` we have, that would absolutely be possible. Maybe add a comment to explain how we got a certain derived color (`/* --scrollbar, but 15% lighter */`).
It's a little less convenient (instead of changing `--scrollbar-thumb` and be done, we'd also have to manually get the derived versions on some color manipulation website or by fiddling with the HSL color picker, for example) but still shouldn't be much of an issue I think.

2. Syntax here would actually be:

```sass
$base-color: #03a7ff;
:root {
  --base-color: #{$base-color};
  --derived-color: lighten($base-color, 20%);
}
```
...because CSS variables can be set to basically anything including *"$"*, we have to explicitly tell Sass to interpolate the value using `#{}`. (Same would apply if we'd assign variables from within the partials)  

I'm not too fond of this I must say. Yes, our Sass variable declarations remain the same, but we now maintain at least double the amount of variable sets. I feel it's a little similar to my previous approach of intermediate files: you can't use the Sass you write directly, but have to do a little mental gymnastics. In the previous case, contributors had to remember not to use the file location of variables files directly but instead point the import at the intermediate location, with this alternative solution they'd have to remember not to use the (intermediate) Sass variables directly, but to first correctly redeclare them as custom properties (potentially in every partial that needs them) and then reference them as such.
Maybe this is way less of a deal than I think it is though, I must admit that this mostly *feels* wrong, without super strong arguments to rationalize it.

But actually there's a third, more radical option...

3. Shocker: **drop Sass** 😳

This entire problem exists due to Sass always reading imports from the file system, without providing any option to pre-process imported files or hook into the loading resolution (as far as I know, happy to be corrected here).  
Since we're only using it for `@import` and `lighten()/darken()` anyway, we could easily replace these with [`postcss-import`](https://github.com/postcss/postcss-import) and [`postcss-color-mod-functions`](https://github.com/jonathantneal/postcss-color-mod-function).
`color-mod()` has different syntax (`color-mod(#000, lightness(+5))` instead of `lighten(#000, 5%)`) but works just fine, you can toy with the color-mod options [here](https://colorme.io/).

This fixes the problem with variable compilation order because
  * `color-mod()` resolves variables passed to it by default so the problem solves itself.
  *  Should we ever want to use some plugin/function/mixin that *doesn't* handle variables on its own, PostCSS allows us to apply a transform to just a part of our CSS, so we could compile the variables files but not the rest. This means we're not *dependent* on `color-mod()`'s built-in variable support.

I know that this is quite a major change so I merely present it as an option, all of this is up to you guys to decide of course (cc @kognise  ) – I don't want to seem like I ruthlessly plow through this code base and leave no stone unturned. But think it through – I'm just not sure that carrying around the baggage of two different kinds of variables/build systems just to use Sass's `lighten()` and `darken()` is worth it. 😅  

Anyhow, an implementation can be found here: https://github.com/jonaskuske/water.css/commits/feat/replace-gulp (the commit updating the gulpfile is the important part)

### Gulp

> I think that our styles function is trying to do too much now.

100%.

>  I don't mind cleaning this up, I've got some ideas in mind and I'm more comfortable with Gulp.

Awesome, thank you!

### Size concerns

You're right, gzip should do wonders here! I think we could also advertise the gzipped size of `water.css` – I think it's a bit dishonest for JS packages as the browser will still have to parse and compile the *uncompressed* JavaScript, but since parsing small CSS stylesheets has (as far as I know) negligible impact on performance, it's totally fair there imo.

Just tested it: *'gzip only'* is `1385 bytes`, *'minify vars + gzip'* is `1312 bytes`. I don't think we should minify CSS variables and thus prevent runtime theming because of 70 bytes, honestly!

### Deploys

By using npm as means of distribution we could add `dist/` to our `.gitignore` and entirely exclude build files from the repo. To deploy, an admin with access to the npm package would simply run `npm deploy`, the prepublish script would compile the CSS and it would be pushed to npm as a new version.  
Alternatively, we could automate this using one of the free CI/CD solutions (GitHub actions, Travis, Circle CI, Netlify folks might even offer this themselves?) so every time something gets merged into `master`, it'll be built and deployed to npm automatically.

**Comment by kylejrp** [comment]
### Color Functions

> I must admit that this mostly feels wrong, without super strong arguments to rationalize it.

Yeah, I agree that it feels a little hacky because we're making a tool do something it wasn't really meant to do. We're kind of between two systems there. We could try to structure it and comment it really well so that it seems intuitive, but it's effort to make this work effortlessly.

> drop Sass

Oh yeah, I love the idea of dropping Sass! I'm actually the one who made the pull request for it back in #9. I was the one ruthlessly plowing through the code base!

Sass was introduced to solve the theming problem. The CSS rules between the dark theme and light theme were being repeated, so Sass was proposed to fix this. (`lighten()`/`darken()` were bonuses.) PostCSS and CSS Variables solves the problem much better than the originally proposed Sass solution.

You're right, we're only using it for the `@import` and `lighten()`/`darken()`. You've proposed great alternatives in PostCSS plugins and I don't think the syntax change is a big deal. To me, this feels like a straight upgrade to the project!

The only complaint I could possibly have is that `color-mod` _was_ in a CSS spec, but was removed for reasons like having poor syntax. I can look past this though and pretend it's not a postponed CSS feature and is instead a magic PostCSS plugin function. 🙈 We'd only be using it in the two places anyways.

I'm really all for dropping Sass, I think it simplifies our source files and gulpfile and it's definitely worth the jump.

### Size Concerns

I agree with your thoughts. I'm thinking the same thing in that's it's a bit cheaty for JS packages, but is okay for CSS. I like that we're leaving our code readable by having gzip handle the variable names instead.

### Deploys

Thanks for the explanation. This sounds like a good plan and we should pursue this in #41 and #64. I like the idea of having CI/CD take care of this.

### Going Forward

You've got some awesome well thought out ideas here. Great work!

Can you make a pull request for https://github.com/jonaskuske/water.css/commits/feat/replace-gulp or merge that branch into `jonaskuske:feat/css-variables`? I think we should go forward with your plan to go all-in with CSS Variables.

**Comment by jonaskuske** [comment]
> The only complaint I could possibly have is that color-mod was in a CSS spec, but was removed for reasons like having poor syntax. I can look past this though and pretend it's not a postponed CSS feature and is instead a magic PostCSS plugin function. 🙈

Yep, it's a pity :(
But we've used a magic color function before and we use a magic color function now, the only difference is that our new magic function knows how to deal with our (non-magic) variables. So we're not losing anything 👍🏻

> Can you make a pull request for https://github.com/jonaskuske/water.css/commits/feat/replace-gulp or merge that branch into jonaskuske:feat/css-variables?

I merged the branch. Feel free to comment, review, clean up, go wild. 😀

**Two more notes, up for discussion:**

### Size report

I added [`gulp-sizereport`](https://www.npmjs.com/package/gulp-sizereport) to get an overview of the filesizes including gzipped size in the end. It's pretty cool, also allows us to set size limits and warn or even fail the build if we exceed them 😅

Anyhow, I noticed that the current bytediff logs aren't giving us the correct final file size as they measure after minification but before source map injection, so the final `/*# sourceMappingURL=... */` comments are not included.
Also, they don't log reported sizes in strict sequential order anymore, don't know why. It looks a bit ugly and is harder to read, though.

We might want to fix the current bytediff pipes, remove them entirely, or make them conditional so e.g. they only log sizes when using a new build script `yarn analyze`.

### Change how we handle standalone builds & add `*-legacy.standalone.css`

Since we found that we can ship unminified variables and thus enable runtime theming for our users, our standalone builds don't quite cut it anymore: they sacrifice theming for browser support.
Because of this, **I propose we have `dark.standalone.css` & `light.standalone.css` use CSS variables as well, which would allow them to be themed.** (file size: `1.14kB` -> `1.28kB` gzipped)
The versions with legacy browser support would be **`dark-legacy.standalone.css`** and **`light-legacy.standalone.css`** respectively.

This might seem excessive, but means we have a very consistent naming schema covering all eventualities:
`[dark|light][-legacy?][.standalone?][.min?].css`

In the interactive version selection I mocked up, implementing this change shouldn't be much of an issue: instead of the checkbox *"Need IE?"* disappearing when selection "standalone", it'll simply always be visible.
The README section will obviously end up larger than the current installation instructions, but if we separate *"Quickly grab a link"* and *"Advanced options"* as is proposed for the interactive selection too, I think it is fine. Here's my suggestion:
___

# Installation

### 🌙 Dark theme:
`<link rel="stylesheet" href="https://unpkg.com/water.css/dark.min.css">`

### ☀ Light theme
`<link rel="stylesheet" href="https://unpkg.com/water.css/light.min.css">`

<br>

### Other options
> ⚡ An interactive version selection is available [here](#)!

#### Enforce a theme and ignore `(prefers-color-scheme)`
For the main versions, `dark` or `light` is only treated as a *default theme*: if a user has a system-wide preference for either dark or light mode on their device, `water.css` will respect this. If you want to avoid this behavior and enforce dark or light theme, append `.standalone` to the theme prefix, e.g. `dark.standalone.min.css`. 

#### Want to support Internet Explorer?
Sure, just extend the theme prefix with `-legacy`, e.g. `dark-legacy.min.css`.
Be aware that these versions **do not support** [runtime theming](#theming) as they use hard coded values rather than variables. Additionally, if you use a legacy version that is not standalone, we recommend [you add the respective preload tags to improve load times](#).

#### Unminified builds
All versions are also available as unminified stylesheets, which can be handy during development.
Simply remove the `.min` from the file name.

> 💡 The file names of the various options follow this schema:
> `[dark|light][-legacy?][.standalone?][.min?].css`

<br>

# Contributing

...

# Theming
...

**Comment by kylejrp** [comment]
Hey @jonaskuske! Sorry for the delay on looking at this again.

I want to try to get this merged in sooner than later. Moving to CSS variables would break any pending and future merge requests, so I don't want this to sit longer than it has to. We should merge exactly what we need to here and worry about other things like changed documentation and unclean code.

Here's our steps:
1. Get @kognise's approval for changing from SASS to CSS Variables, noting that there are some breaking compatibility changes for IE11 support
2. Identify any changes we still need to make. In scope items are things that we need to get the CSS variables compiling into `light.css`/`dark.css`. This will include things like any new merges that aren't included in the migration. Out of scope items are things that make the gulp pipeline easier to work with, cleaning up variable names or other code, etc.
3. Make in-scope changes
4. Create new issues for out of scope changes
5. Merge into master
6. Identify any pending merge requests that will need to be updated to CSS variables

@jonaskuske is there anything I've missed in my steps above? Can you help me compile a list of in scope and out of scope items? We can then work together to make the in scope changes and log new issues for the out of scope changes. I'll ping @kognise to make sure he's on board with everything.

If an NPM release isn't absolutely necessary to get things compiling, I think we should tackle that in a separate issue like #64. The separate IE11 compatibility stylesheet documentation should also be handled in a separate issue.

**Comment by kognise** [comment]
@jonaskuske thanks so much for all of this! I totally approve of replacing SASS with CSS variables and think dropping SASS altogether is a great idea.

One thought about the thing you said with publishing to NPM and dropping `dist/` - this will break all websites getting Water.css through jsdelivr. Are there any possible workarounds to this?

**Comment by kylejrp** [comment]
You're right, it breaks jsDelivr, but I don't think it's as hard of a break as expected.

If you remember all the way back to the project release, the file was originally `/water.css` instead of `/dist/light.css` and `/dist/dark.css`. However, the jsDelivr link still works for the original `/water.css`:
https://cdn.jsdelivr.net/gh/kognise/water.css@latest/water.css

So, if we remove the `/dist` folder and build through npm instead, anyone who was using the old jsDelivr link that used `/gh/` in the path will still receive the same version as before. They won't get updates, but that's okay in my opinion since we're making breaking changes.

Going forward, our documentation would use the npm version of the jsDelivr link:
`https://cdn.jsdelivr.net/npm/kognise/water.css@2/dist/dark.min.css`

I'd also recommend that with this breaking change, we set the release version to 2.0.0 and advise users to target that major version with the jsDelivr link (`kognise/water.css@2`). Then, they'll still get updates, but we won't have to worry so much about breaking changes when we inevitably make a breaking change and have to go to 3.0.0. 

If we're looking for more stability for users, we could target the major/minor version (`kognise/water.css@2.0`), but I think it's nicer to have new styles automatically rolled out to users. 🤷‍♂️ Maybe people an make their own decisions about the versions they target?

**Comment by jonaskuske** [comment]
I'll try to work on getting this up-to-date this evening :)

**Comment by jonaskuske** [comment]
Alright @kylejrp, I updated the PR. 

> 2. Identify any changes we still need to make. In scope items are things that we need to get the CSS variables compiling into light.css/dark.css. This will include things like any new merges that aren't included in the migration.

I updated the PR to include the new merges (padding and color adjustments). I manually recreated them, as can be seen in the commit logs. I then merged master into this branch using the `ours` strategy so that when we merge this feature branch into master, it should completely replace master without a conflict.

> 3. Make in-scope changes

Any other in-scope changes? I *think* we could just bump the version to 2.0.0 and merge this. Anyone on `latest` would start to receive the new (`--variable`-powered and `prefers-color-scheme`-aware) builds, anyone using a properly versioned jsDelivr URL should not see any changes, as the jump to v2 is a breaking change. (assuming jsDelivr paired with GitHub-based hosting handles semantic versioning properly)
  
I updated the README with information about the different builds and added a notice about the theming guides etc. being out-of-date for now. Please take a look and say what else we need to change there before we can merge.

> 4. Create new issues for out of scope changes

I'd say these out-of-scope issues are:

- [ ] Update theming guide
- [ ] Add/Update Contributing guide
- [ ] Update demo/landing page with version picker
- [ ] Add separate `browserslist` for modern builds
- [ ] Code cleanup where necessary
- [ ] npm release + CI-powered automatic build step

Any of this critical even before the merge?

**Comment by kylejrp** [comment]
Moving `index.html` into `docs/` broke the Netlify build. Lets do this in a separate pull request as we'll need @kognise to mess with the Netlify config.

The rest of your changes look great! Thanks for all of your hard work on this pull request, you've done a good job. 

I'll merge and bump the version to 2.0.0 and undo the change to `index.html`. I'll open up new issues for the out of scope items. I don't think jsDelivr will update their semantic versioning under their `/gh/` path until a new release is created in Github.

@kognise, when you can, can you create a 2.0.0 release in GitHub? 🚀

**Pull request merged**
