### PR TITLE
Bookmarklet theme toggle

### PR DESCRIPTION
**Pull request by HarshitJoshi9152**
this works good, but i dont know how to go about the x-position placement of the toggle button.
as of right now i guess its placement would seem pretty awkward on wide screens (just 50px from the right).

### CODE REVIEW

**Comment by kognise** [comment]
This is great! I'll fiddle with the design.

In the meantime, I feel like putting CSS variables inside the code isn't very futureproof and is a bit janky. What do you think of just pulling in either the dark/light stylesheet from the script? It'll be a bit more in network requests but Water.css is quite light anyways.

**Comment by HarshitJoshi9152** [comment]
Yup totally agree, it would clean up the code by a lot 👍

**Comment by HarshitJoshi9152** [comment]
one thing i forgot to mention is that i have used [https://caiorss.github.io/bookmarklet-maker/](https://caiorss.github.io/bookmarklet-maker/) instead because i couldnt get [https://mrcoles.com/bookmarklet/](https://mrcoles.com/bookmarklet/) working.

**Comment by kognise** [comment]
Awesome! I cleaned a couple things up, and fixed it to use `light.css` instead of `water.css`. Any other changes before we merge this?

**Comment by HarshitJoshi9152** [comment]
Nope, all good

**Review by kognise — APPROVED** [review]

**Pull request merged**
