### PR TITLE
Add husky and lint-staged for commit automation.

### PR DESCRIPTION
**Pull request by jackson-elfers**
Using the already existing standard and stylelint, I've added their commands to lint-staged to lint and format (js and src/css) upon commit. Let me know if anything needs revising. Thanks JE @kylejrp

### CODE REVIEW

**Comment by kognise** [comment]
Oof, sorry for being a slowpoke. The upcoming 2.0 release updated the linting workflow a bit, do you think it would still be a good idea to add lint-staged?

**Comment by kimulaco** [comment]
@kognise I think a good idea to add lint-staged. Because contributors can quickly find mistakes. 
Linting can also be done with CI. However, compared to lint-staged, it is delayed in discovering mistakes.

**Comment by kognise** [comment]
@kimulaco the alternative is just to add `yarn lint` to a precommit hook as well as CI, without the dependency of `lint-staged`.

**Comment by jonaskuske** [comment]
Yeah, the advantage of lint-staged is that only staged files are linted (not the entire codebase), so it's faster and you can switch to some new style rules piece-by-piece, making sure that all new and updated code adheres to the linting rules but the rest of the code base isn't touched.
I think we need neither of those features, so yeah, just adding the lint script should probably work out just fine. 👍

**Comment by kimulaco** [comment]
I didn't have enough knowledge...!
I learned a lot. Thank you!

**Comment by kognise** [comment]
I added husky in fa7e9f5c51c85604609904fec83091919c61b8a8, thanks y'all.

**Pull request closed without merging**
