### PR TITLE
Added Community Themes

### PR DESCRIPTION
**Pull request by kylejrp**
Added Darker by JackFly26 to close #26

### CODE REVIEW

**Comment by kognise** [comment]
Beep, boop, Netlify, build.

**Comment by kognise** [comment]
NEEEEEEETLIFY!

**Comment by kylejrp** [comment]
I think we're okay - they're not "Official Themes", they're "Community Themes". I think it's okay for them to go out of date. The community can always make pull requests on those forks to bring them up to speed, or make their own forks that will be kept up to date.

**Comment by JackFly26** [comment]
Also since mine is just extending `dark.css` you could make a way to have it sync to the current `dark.css`.

**Comment by kognise** [comment]
@JackFly26 Probably not - we aren't owners of your repository.

**Comment by kognise** [comment]
@JackFly26 Would you mind adding your theme into a seperate file, so it's like `darker.css` or something instead of `dark.css`?

We'll work on adding community theme requirements.

**Comment by kylejrp** [comment]
We should wait for #71 before adding community theme requirements. This makes theme contributions a lot easier.

**Comment by kylejrp** [comment]
Looks like Darker by @JackFly26 is 7 months out of date and would probably need to be updated to the new CSS variables methodology to be included in a community themes listing.

We can track the guidelines around community theming in #147

**Pull request closed without merging**
