### PR TITLE
Publish to NPM

### LINKED ISSUE #41: Publish to npm
It might be nice to have water.css published to npm with every release. Then, users can install it using `npm install water.css` and include it in their projects without referencing a CDN.

This would mean we would have to update the `package.json` version semantically with every release as well.

### PR DESCRIPTION
**Pull request by kognise**
This PR contains changes necessary to smoothly publish Water.css to NPM. This closes #41! Does anything else need to be changed?

### CODE REVIEW

**Comment by diomed** [comment]
buttons wont be in this version?
please merge and release :P

**Comment by diomed** [comment]
https://github.com/kognise/water.css/issues/52

would really like to see this applied in current one

**Comment by kognise** [comment]
@diomed we'll work on getting those into the next release!

**Comment by diomed** [comment]
welp. I hoped to see it sooner, rather than later. I mean, you could put it off until tomorrow, and that are small changes really.

**Comment by kylejrp** [comment]
Hey @kognise, do you need any help with this? I'm not super familiar with NPM but I could learn some more about it to help get this published!

**Comment by jonaskuske** [comment]
What's the status here?

Would be happy to pick this up, update it to match the current master and look into [Netlify Continuous Deployment](https://www.netlify.com/docs/continuous-deployment/) so we'll get automatic releases to npm whenever something lands in master.

I imagine the setup (in GitHub) would look like this:
  - branch `dev`: The development branch. PRs from contributors will be merged into this branch.

  - branch `master`: The latest stable & published version. When we want to publish a new version, we merge the changes from `dev` into this branch, Netlify picks up the changes, runs `gulp build`, publishes a new version to npm and re-deploys the documentation site.

We could additionally publish the `dev` branch to npm under a different tag, e.g. `water.css@dev` or `water.css@next`. This way we'd have an automatic beta/canary version up on npm.

**Comment by jonaskuske** [comment]
Steps I see here:

- [ ] Get this branch up-to-date with master
- [ ] Add `dist/` folder to `.gitignore`
- [ ] Set `prepublishOnly` script to `yarn build` so the package is automatically built whenever we publish
- [ ] Update Netlify config so it runs `yarn publish` on every [production deploy](https://www.netlify.com/docs/continuous-deployment/#branches-deploys)

Additional and/or optional steps:
- [ ] Update Contributing guide
- [ ] Update Netlify config to run `yarn publish --tag dev` on every [branch deploy]((https://www.netlify.com/docs/continuous-deployment/#branches-deploys)) from `dev` branch

Am I missing anything?

**Comment by kylejrp** [comment]
I started the [2.0.0 milestone](https://github.com/kognise/water.css/milestone/1) for all the issues that should be merged before publishing version 2.0.0 to NPM.

Once all issues there have been closed, we will be able to release on NPM! 🎉

**Comment by diomed** [comment]
so glad this is dragging along whole year.
shows your true commitment to this project

**Comment by andrewsosa** [comment]
Does this PR need any help? This PR will have been open for almost a year next month.

**Comment by kognise** [comment]
Closing this because I updated the package.json in 1297b75c5cc7dbf70e9fd06accbc2be8932352f1 and we should probably continue the conversation in #187

**Pull request closed without merging**
