### PR TITLE
Add style guidelines/linter

### LINKED ISSUE #73: How about adding a config file, such as linter?
I saw this PR(https://github.com/kognise/water.css/pull/23).
I think it is a good idea to add Linter.
Currently, gulpfile.js does not standardize the presence of semicolons and the style of indent.

However, it is inefficient to create all linter settings manually.
So I suggest creating a config based on [JavaScript Standard Style](https://standardjs.com/)([eslint-config-standard](https://github.com/standard/eslint-config-standard)).

In addition, I think that it is also effective to set up the next.

- [stylelint](https://stylelint.io/)
- [EditorConfig](https://editorconfig.org/)

If you have an opinion please!
If you are considering adding, I can give PR. (It will take a little while.)

### PR DESCRIPTION
**Pull request by kognise**
This is PR closes #73.

To duplicate my comment in the original issue:
> I love Standard, but @JanSchneider1 mentioned that forcing semicolons might be more beginner friendly. I don't agree or disagree, but we should consider this.

We should also considering adding these linting rules to Gulp so developers can get live feedback. Linting should also be added to CI.

### CODE REVIEW

**Comment by kylejrp** [comment]
No preference for semicolons for me. I'm fine with just using vanilla Standard.

Lining information should be added to the contributor guidelines (#110). Plugins/settings for IDEs like VSCode, commands to run, etc.

**Comment by kognise** [comment]
Ok, so I've added some basic linting. Things to think about:

- Potentially adding style linting to a CI pipeline
- Adding style linting the Gulp
- EditorConfig support - do we want this?

**Comment by kylejrp** [comment]
I think those three thoughts are worthy of their own issues/pull requests. 

I think we should merge the basic limiting and invite the community to contribute to the three issues above. 

Does this lint the doc files as well?

**Comment by kylejrp** [comment]
I'm merging the basic linting in. I'll open up new issues for the three recommendations above.

**Pull request merged**
