### PR TITLE
Gulp build tools

### PR DESCRIPTION
**Pull request by kylejrp**
I replaced the previous development server with a souped-up gulp build pipeline. Now you're playing with power! 😎

### Gulp
Gulp replaces the previous compiling of the sass files and also handles the development tools. Gulp has lots of other extensions for things like html templating and minification that the demo page could take advantage of in the future.

#### Sourcemaps
Devtools will now show you the original sass file the rule came from instead of just the full .css file:
image

It will even show you the original Sass file in devtools:
image

**Note:** this makes the dark.css/light.css look really big in devtools, but that's because it's also downloading the sourcemap file. The actual .css file is still small when using in production.

#### Autoprefixing
You can forget about browser prefixes now - autoprefixer will handle them! I've put a recommended set of supported browsers in the package.json. You can see the coverage here. Feel free to modify!
https://browserl.ist/?q=last+1+version%2C+not+dead%2C+%3E+0.2%25

#### CSS Minification
postcss/cssnano are handling css minification. I'm using their "safe" defaults, but they could be tuned even further to provide some even better minification.

#### Browser Sync
This does the live reloading / development environment that you had previously set up with `dev.js`. However, there's no more server code for you to maintain! This should automatically stream changes to your browser when you have it open. It automatically launches and watches `index.html` and the sass files when running `yarn dev`.

### CODE REVIEW

**Comment by kognise** [comment]
*gulps*

sorry, bad pun

**Comment by kognise** [comment]
*cough cough* Anyways, thanks so much! How will the source maps be eliminated in production?

**Comment by kognise** [comment]
Also, what stricter options for cssnano do you recommend?

**Comment by kylejrp** [comment]
I noticed that all of dev.js got moved into index.js, but we don't need that anymore because gulp is running the server.

Source maps are eliminated in production because they're in a separate file (dark.css.map and light.css.map). The only time these are downloaded are when devtools are open. So, in production, only dark.css is downloaded and dark.css.map goes unused.

cssnano has an [optimization guide](https://cssnano.co/guides/optimisations) for some of the unsafe options that aren't included by default. I haven't used any of these before.

**Comment by kognise** [comment]
Aaaawesome! About autoprefixer - it increases file size substantially, to over 2kb!

**Comment by kylejrp** [comment]
Oh, yikes! We might want to tune the browserlist then. There might be a browser we can remove that's adding a lot of prefixes. It's just a matter of what you think we should support!

**Comment by kognise** [comment]
Setting the percentage to `> 5%` yields much better results. Pushing a change right now. About the index.js, that's to make the repl.it button work. I update it to just start the gulp dev server.

**Comment by kognise** [comment]
Ready to merge?

**Comment by kylejrp** [comment]
There's a few browsers in here that we could probably drop - they're at 0%: https://browserl.ist/?q=last+1+version%2C+not+dead%2C+%3E+5%25

**Comment by kognise** [comment]
How does browserlist math work? Is 0% now greater than 5%? 🤔

**Comment by kylejrp** [comment]
I think they're all OR's, unless they're NOT rules, then they're ANDs. Eg:

`("last 1 version" OR "> 5%") AND ("not dead")`

I'll work on a more optimal browserlist and flesh out the size measuring a bit more. I think it's better to measure the autoprefixing and the minifying separately so they don't cancel each other out.

I'll get something that we can merge tonight!

**Comment by kognise** [comment]
@kylejrp Thanks! What's "tonight" to you? It's 11:30pm for me right now.

**Comment by kylejrp** [comment]
Oh whoops, I'm on the west coast - sorry for keeping you awake! Changes are up now. Found a browserlist that has 89% coverage, but only gains 144B. It was Android Browser 4.4.3 that was holding us back!

https://browserl.ist/?q=defaults+AND+not+android+4.4.3

**Comment by kognise** [comment]
Great! Silly android. And no problemo :P

**Comment by kognise** [comment]
:shipit:

**Comment by kylejrp** [comment]
:shipit:! 

Hah, sorry for my terrible javascript styles. Might be worth it for you to configure a linter so you don't have to manually go through and fix my changes.

**Pull request merged**
