### PR TITLE
Add address styles

### LINKED ISSUE #44: <address> and links inside
We can style the `<address>` element, or more specifically, the links inside!

MDN has good documentation:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address

They've put icons before each type of link by using the following selectors:
```
a[href^="mailto"]::before {
    content: "📧 ";
}

a[href^="tel"]::before {
    content: "📞 ";
}
```

We could probably do something more interesting here, but I'm not a great designer and nothing's coming to mind. Any ideas?

### PR DESCRIPTION
**Pull request by kognise**
This should close #44. Adds styles for addresses and mailto/tel links. Things to consider:

- I'm currently using the :email: emoji, but it displays incorrectly in some fonts. I prefer it over :e-mail: but the latter seems to have more support.
- Are there other protocols besides `tel` and `mailto` we should think about?

### CODE REVIEW

**Comment by kylejrp** [comment]
> I'm currently using the ✉️ emoji, but it displays incorrectly in some fonts. I prefer it over 📧 but the latter seems to have more support.

I wonder if there's such things as emoji semantics too? Haha.

I think either is fine really. The ✉ symbol is a general envelope, while the 📧 symbol is explicitly an email symbol. It's all aesthetics though, I'm not sure that it matters.

Do you have an example/screenshot of when the ✉ symbol looks bad in one of the fonts in the Water.css stack?

> Are there other protocols besides tel and mailto we should think about?

I'm not seeing any others after a quick search.

**Comment by jonaskuske** [comment]
According to [CSS-Tricks](https://css-tricks.com/the-current-state-of-telephone-links/#article-header-id-3) there also is `sms:`, `callto:` and `fax:`, but with spotty browser support so we can probably ignore it.

The only other thing we could consider is adding icons for download links, e.g. a document icon for `a[download][href$=".pdf"]`.

**Comment by kognise** [comment]
I added `sms:` styles. Any last things or can we merge?

**Comment by kognise** [comment]
:shipit:

**Pull request merged**
