### PR TITLE
[WIP] README update / Theming section

### LINKED ISSUE #83: Update Theming Guide in README.md
The source files for water.css were changed from SASS to just plain CSS using CSS variables. See the full details on #71. 

This made the theming guide in README.md out of date. It needs these minor updates: 
- The references to SASS should be removed.
- The variables should no longer be SASS variables. Instead of listing all our variables, we can just link to `src/variables-dark.css` or `src/variables-light.css`
- How to edit CSS variables in browser to test theming
- Basic Theming: How to override these CSS variables with your own stylesheet
- Advanced Theming: Information about setting up a custom build file in `src/builds/` should be added. There's a few types of builds that we should have descriptions for (see #71):
  - Normal (Like `dark.css`)
  - Standalone (Like `dark.standalone.css`)
  - Legacy (Like `dark-legacy.css`)
  - Legacy Standalone (Like `dark-legacy.standalone.css`)
- Policy around support for community themes from #26/#42

### PR DESCRIPTION
**Pull request by jonaskuske**
This PR brings a couple changes to the README, the main one being the addition of the Theming section:

  - Restructured heading section a bit (badges at the top, centered...)
  - Changed tagline to "a drop-in collection of CSS styles..." which works better imo, I'd suggest also making this change for the repo description 
  - Replaced "Good code quality" with "Themeable" in Goals, which I think is more relevant to most users
  - Added the theming section for both runtime theming and compilation

Note that this README is currently refering both to the Contributing Guide as well as the new demo page with the version picker and neither exists yet, so **don't merge yet** please :)

Preview entire new README without git diff: https://github.com/kognise/water.css/blob/2183c463bb80ec897af229cbbc6fa0f555d22fee/README.md

fix #83

### CODE REVIEW

**Comment by kylejrp** [comment]
Looks great so far! I'm a fan of the changes.

I agree with removing "good code quality" only because that's a hard metric. Themable is a better metric. 

Another goal might be "easy to contribute", but there would be some cleanup work to do before we could feel good about adding it.

Like you said we'll need the contributing guide made for this.

**Comment by jthegedus** [comment]
As someone who cares deeply about READMEs these changes improve the experience for users significantly. Thanks for making these adjustments, should help me convince others to use this.

**Comment by kylejrp** [comment]
@jonaskuske The contribution guide is now merged into master. Are you able to resolve the conflicts so we can get this merged in now? 😄

**Comment by jonaskuske** [comment]
Sure, I'll get to it tomorrow! :)

**Pull request merged**
