### PR TITLE
Add documentation for browser support

### LINKED ISSUE #233: Add documentation for elements Water.css supports that some browsers don't
See #231 for context

We should include in either the example page or our readme that we style some elements like `<dialog>` that are not supported by other browsers. You can check [caniuse](https://caniuse.com/dialog) for browser support for HTML elements.

We would take a pull request that would add this to the documentation. Ideally, you would check all the HTML elements in the example page and see what elements we style that are unsupported by major browsers. I suspect that it's just `<dialog>`, but it would be nice to confirm.

### PR DESCRIPTION
**Pull request by KaustubhDamania**
Fixes #233 
Update README.md by adding a table showing the HTML elements styled by Water.css and not supported by one or more browsers.
Also, the `details` element is [not supported by IE](https://caniuse.com/mdn-html_elements_details_open) but Water.css styles it.

### CODE REVIEW

**Comment by KaustubhDamania** [comment]
Can anyone review this?

**Comment by KaustubhDamania** [comment]
@kylejrp can you review this?

**Comment by kylejrp** [comment]
Thanks for your contribution @KaustubhDamania! I'm unavailable right now but will review this when I can, especially if this is something you need merged to qualify for Hacktober. Thanks for looking into this for us!

**Comment by KaustubhDamania** [comment]
@kylejrp can you review this? :sweat_smile:

**Comment by KaustubhDamania** [comment]
@kylejrp can you review this? sweat_smile

**Comment by kognise** [comment]
I'll take a look, sorry, been super stressed out recently. Don't need to
bother poor Kyle!

**Comment by KaustubhDamania** [comment]
@kognise okay, just that it wasn't reviewed since a long time hence I asked again :sweat_smile:

**Review by DonovanDiamond — APPROVED** [review]

**Comment by kognise** [comment]
Honestly, I'm not in favor of merging this for the following reasons:

- Makes maintenance a massive pain in the ass, the README would have to be constantly updated
- The information is publicly available, and site developers are the ones to decide what elements they're using either way

I appreciate the PR - I'm gonna close it, but if you disagree with me feel free to continue the conversation!

**Pull request closed without merging**
