### PR TITLE
added contrast in buttons

### LINKED ISSUE #228: Accessibility of Buttons?
#225 fixed the buttons colors being indistinguishable in tables, but when I checked the color contrasts, they're still a little lacking.

I'm thinking that we need to make the color contrast even stronger. Here's the contrast ratio I'm seeing in each theme/background combination using a [contrast checker](https://webaim.org/resources/contrastchecker/):
image image

| Background | Light Theme | Dark Theme |
|---------------|--------------|---------------|
| Light             |  1.14:1        |    1.16:1      |
| Dark             |   1.07:1        |    1.06:1     |

It seems like a color contrast ratio of [3:1 is recommended for accessibility with these elements](https://www.w3.org/TR/WCAG21/#non-text-contrast).

It seems like this contrast might be lacking on `<button>` elements on the normal backgrounds too.

I'm not a designer, so I would love if someone with a mind for colors would be able to provide some guidance here. 😅

### PR DESCRIPTION
**Pull request by HimanshuPandey2002**
changed buttons colours , for light mode button color is now #d0cfcf and its hover color is rgb(170, 170, 170) and for dark mode the button color is now #0c151c and its hover color is #2f5372.

Closes #228

### CODE REVIEW

**Comment by kylejrp** [comment]
Hey @HimanshuPandey2002, thanks for taking the time to contribute!

You'll need to include a changeset describing the change you've made. See our contributing guide:
https://github.com/kognise/water.css/blob/master/.github/CONTRIBUTING.md

I think this really highlights how some of our other components are failing for accessibility when it comes to distingui[shing ui components](https://www.w3.org/TR/WCAG21/#non-text-contrast). I'm going to get @kognise to review before I merge - we might want to open up new issues for other components if we're happy how the buttons look.

**Comment by HimanshuPandey2002** [comment]
@kylejrp Thanks for telling me about the changeset, I didn't know about that but now I've created the changeset and commit the changes.

**Comment by kognise** [comment]
Thanks for the pull request, and apologies for being so slow! Would you mind changing the hover color to be closer to the base color?

**Comment by HimanshuPandey2002** [comment]
No problem, I can do that

**Review by kognise — DISMISSED** [review]

**Review by kognise — APPROVED** [review]

**Pull request merged**
