### PR TITLE
change netlify domain to .app

### PR DESCRIPTION
**Pull request by shayaulman**

### CODE REVIEW

**Comment by kylejrp** [comment]
This is the email from Netlify describing the change from .com to .app:

> Starting April 14, 2020, sites without a custom domain are being moved from your-site.netlify.com to your-site.netlify.app. New websites without custom domains will also have URLs ending with netlify.app, unless you specify a custom domain.
> 
> It's important to note all of your existing sites will continue to operate properly using their current URLs.
> 
> Why the change? We're investing in the security and stability of our infrastructure, and this step is necessary on that journey.
> 
> There's no action required on your part, but we wanted to inform you well ahead of the change in case you have any questions. Additional details are provided below if you'd like to read more. Thanks for being part of the Netlify community!

There's no breaking changes but this is a good catch. Thanks, @shayaulman!
cc @kognise

**Comment by kognise** [comment]
The site is now aliased to [watercss.kognise.dev](https://watercss.kognise.dev) although the domain is kinda :poop:y - but I think it should be fine to close this for now?

**Comment by kylejrp** [comment]
Should be good as long as:
- you've also got the logo link changed
- the old URLs redirect

**Comment by kognise** [comment]
Closing this because the URL has been updated to [watercss.kognise.dev](https://watercss.kognise.dev) in the upcoming 2.0 release. Thanks for the PR ❤️

**Pull request closed without merging**
