### PR TITLE
Update ::selection

### PR DESCRIPTION
**Pull request by diomed**
`#E0EDF9` as a color better suits and reflects water.css

since blue color is color of clean water

### CODE REVIEW

**Comment by diomed** [comment]
@kognise please merge this

**Comment by kylejrp** [comment]
Hey @diomed,

Thanks for your contribution! Can you run `yarn build` on your branch? Our [contribution guidelines](https://github.com/kognise/water.css#contributing) need the project built again before we can merge any changes.

**Comment by diomed** [comment]
how to do so?
I contribute via github webpage, not via git.

**Comment by diomed** [comment]
also , this is change of hex color value on one line, not something that changes anything to point of breaking it.

**Comment by kylejrp** [comment]
Unfortunately, it's hard to contribute to water.css via the GitHub webpage. It might be easier in the future if we change some of our tools.

If you're new to contributing to open source software, there would be a few steps:
- Install the yarn package manager and Git
- Download your fork to your computer using Git
- Run `yarn` to download all the dependencies for the project
- Run `yarn build` to create all the files in `/dist/`
- Commit your changes back to your fork using Git

Git has a guides on how to fork a repo and make commits:
https://help.github.com/en/articles/fork-a-repo

**Comment by diomed** [comment]
dont know why you have to be so strict about it
all I did was changed a hex color

come on
seriously

**Comment by kylejrp** [comment]
In order for the changes to appear in `light.css` and `light.min.css`, `yarn build` has to be run on the pull request. Right now, the changes are only appearing in `light.scss`.

**Comment by diomed** [comment]
could you do this via my PR?
you already see what  color  I suggested.

**Comment by kylejrp** [comment]
I can pull your branch and run the build, but only when I have time and access to my development machine. We can merge this faster if you're able to run the builds and make the commits.

If you're not able to run the build yourself, please let me know and I can make a note to run the build on this branch the next time I can.

**Comment by diomed** [comment]
yes, please do so next time you can

**Comment by diomed** [comment]
it's incredible that this minor change takes month+ to add.

**Comment by kognise** [comment]
@diomed I'm sorry if you're annoyed, but a lot of things have been delayed. Over the summer I didn't have any internet connection, so I was unable to work on Water.css. And this pull request isn't the highest priority.

But I'm taking a look at it now, thank you for bringing this PR to my attention again via Discord.

**Comment by kognise** [comment]
Hey @diomed could you please take a look at my feedback above? Thanks :)

**Comment by diomed** [comment]
@kognise can you please merge pr, then I'll see about it and fix it.

**Comment by kognise** [comment]
The highlight color has been updated in the upcoming 2.0 release.

**Pull request closed without merging**
