### PR TITLE
'Darker' theme and squarer buttons

### PR DESCRIPTION
**Pull request by JackFly26**
I added a theme and decreased the border-radius of buttons. What else is there to say? There is less blue in the new colors, and I personally think it looks better.

### CODE REVIEW

**Comment by gruhn** [comment]
I don't think a darker theme or any additional theme is really necessary. I think it makes more sense to find strong conventions.

There are many highly customizable CSS frameworks out there. What makes this one appealing is it's simplicity. Take it or leave it.

**Comment by kylejrp** [comment]
I agree with @gruhn - simplicity is key here. However, theming is there if people want it and I think it's still important to recognize the work that @JackFly26 put in. 

Maybe we could link to forks that have created their own themes? Then, we're not stuck supporting several themes as we add new elements, but we can still accept contributors that create their own themes.

This is kind of like how [Bootstrap](https://getbootstrap.com/) has a separate site linking to [Bootstrap themes](https://themes.getbootstrap.com/) that the community has created.

What do you think @kognise?

**Comment by kognise** [comment]
I agree with @gruhn that we probably don't want to merge this, but @kylejrp had a good idea!

@JackFly26 do you wanna make a fork with your awesome theme that'll get mentioned probably in the readme and on the website?

**Comment by JackFly26** [comment]
I already forked. That's what the or is from. You mean only with that theme?

**Comment by kognise** [comment]
Closing in favor of #42

**Pull request closed without merging**
